services:
  app.filters.mediatheque.user_configuration.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { name: 'exact' } ]
    tags: [ 'api_platform.filter' ]
    autowire: false
    autoconfigure: false
