api_platform:
    enable_swagger_ui: false
    title: "Mediatheque API"
    doctrine:
        enabled: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
