security:
  enable_authenticator_manager: true
  providers:
    users_in_memory: { memory: null }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    docs:
      pattern: ^/docs/$
      security: false
    main:
      lazy: true
      stateless: true
      custom_authenticators:
        - App\Security\OAuth2Authenticator

  access_control:
    - { path: ^/docs/$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
