security:
  enable_authenticator_manager: true
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: id
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    docs:
      pattern: ^/docs/$
      security: false
    file_download:
      pattern: ^/(audio_book_files|book_files)
      methods: [GET]
      lazy: true
      stateless: true
      custom_authenticators:
        - App\Security\FileDownloadAuthenticator
    main:
      lazy: true
      stateless: true
      custom_authenticators:
        - App\Security\FileDownloadAuthenticator
        - App\Security\OAuth2Authenticator

  access_control:
    - { path: ^/docs/$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
