resources:
  App\Entity\ElectronicBook:
    attributes:
      normalization_context:
        groups: ['file_read']
    itemOperations:
      get:
        controller: App\Controller\ElectronicBook\Get
      get_raw_data:
        method: GET
        controller: App\Controller\Book\GetElectronicBookRawData
        path: /electronic_books/{id}/raw
      delete:
        controller: App\Controller\ElectronicBook\Delete
    collectionOperations:
      post:
        controller: App\Controller\ElectronicBook\Post
        defaults:
          _api_receive: false
        swagger_context:
          consumes: ["multipart/form-data"]
          parameters:
            - name: file
              in: formData
              type: file
              description: "The book to upload"
