api_platform:
    enable_swagger_ui: true
    enable_swagger: true
    oauth:
        enabled: true
        clientId: 'swagger'
        clientSecret: '%env(resolve:KEYCLOAK_SWAGGER_CLIENT_SECRET)%'
        type: 'oauth2'
        flow: 'application'
        tokenUrl: '%env(resolve:KEYCLOAK_EXTERNAL_BASE_URL)%/realms/mediatheque/protocol/openid-connect/token'
        authorizationUrl: '%env(resolve:KEYCLOAK_EXTERNAL_BASE_URL)%/realms/mediatheque/protocol/openid-connect/auth'
        scopes: [ ]
