resources:
  App\Entity\Book\ReferenceGroup\Book:
    shortName: ReferenceGroupBook
    attributes:
      denormalization_context:
        groups: ['referenceGroupBook:set']
      normalization_context:
        groups: ['referenceGroupBook:get']
    itemOperations:
      put: ~
      get: ~
      delete: ~
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'referenceGroupBook:list' ]
        filters:
          - App\Filter\Book\ReferenceGroup\Book\ReferenceGroup

