imports:
    - { resource: './packages/api_platform/filters/**/*.yaml' }

parameters:
    keycloak_internal_base_url: '%env(resolve:KEYCLOAK_INTERNAL_BASE_URL)%'
    keycloak_expected_issuer: '%env(resolve:KEYCLOAK_EXPECTED_ISSUER)%'
    meilisearch_master_key: '%env(MEILISEARCH_MASTER_KEY)%'
    meilisearch_internal_base_url: '%env(MEILISEARCH_INTERNAL_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

            string $keycloakInternalBaseUrl: '%keycloak_internal_base_url%'
            string $keycloakExpectedIssuer: '%keycloak_expected_issuer%'

            string $meilisearchMasterKey: '%meilisearch_master_key%'
            string $meilisearchInternalBaseUrl: '%meilisearch_internal_base_url%'

            ApiPlatform\State\ProviderInterface $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Controller/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\SwaggerUi\BackupControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 1 }

    App\EventListener\SwaggerUi\RestoreControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -1 }
