imports:
    - { resource: './packages/api_platform/filters/**/*.yaml' }

parameters:
    keycloak_internal_base_url: '%env(resolve:KEYCLOAK_INTERNAL_BASE_URL)%'
    keycloak_expected_issuer: '%env(resolve:KEYCLOAK_EXPECTED_ISSUER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

            string $keycloakInternalBaseUrl: '%keycloak_internal_base_url%'
            string $keycloakExpectedIssuer: '%keycloak_expected_issuer%'

    _instanceof:
        App\Service\Cleaning\OrphanFileEntitiesFinder\OrphanFileFinderInterface:
            tags: ['mediatheque.cleaning.orphanFileEntitiesFinder']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Controller/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\SwaggerUi\BackupControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 1 }

    App\EventListener\SwaggerUi\RestoreControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -1 }

    App\Service\Cleaning\OrphanFilesFinder:
        bind:
            array $mappings: '%vich_uploader.mappings%'

    App\Service\Cleaning\OrphanFileEntitiesFinder:
        bind:
            $orphanFileEntitiesFinders: !tagged_locator { tag: 'mediatheque.cleaning.orphanFileEntitiesFinder', index_by: 'key', default_index_method: 'getType' }
