resources:
  App\Entity\Book\ElectronicBook\FileDownloadToken:
    shortName: ElectronicBookFileDownloadToken
    attributes:
      denormalization_context:
        groups: ['mediatheque_fileDownloadToken:set']
      normalization_context:
        groups: ['mediatheque_fileDownloadToken:get']
    collectionOperations:
      post: ~
    itemOperations:
      get:
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false
