resources:
  App\Entity\Book\ElectronicBook\Information\Image:
    attributes:
      route_prefix: /electronic_book_information
      normalization_context:
        groups: [ 'electronicBookInformation_image:get' ]
    itemOperations:
      get: ~
      get_file:
        method: GET
        path: /images/{id}/file

    collectionOperations: []
