resources:
  App\Entity\Book\AudioBook\Book:
    shortName: AudioBook
    attributes:
      denormalization_context:
        groups: ['book:set']
    itemOperations:
      put:
        normalization_context:
          groups: ['audioBook:get', 'book:get', 'file_read']
      get:
        normalization_context:
          groups: ['audioBook:get', 'book:get', 'file_read']
      get_file_raw:
        method: GET
        path: /audio_books/{id}/rawFile
        normalization_context:
          groups: [file_read]
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'book:list' ]
