resources:
  App\Entity\Book\AudioBook\File:
    shortName: AudioBookFile
    attributes:
      iri: http://schema.org/Book/BookFile
      normalization_context:
        groups: ['file_read']
    collectionOperations:
      post:
        controller: App\Controller\Book\AudioBookFile\Post
        defaults:
          _api_receive: false
        validation_groups: [Default, file_create]
        openapi_context:
          summary: Create an audio book file to link to a book
          description: Create an audio book file from an uploaded file
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                  - name: file
                    type: file
                    description: The file to upload
                    required: false
    itemOperations:
      get: ~
