resources:
  App\Entity\Author:
    attributes:
      denormalization_context:
        groups: [ 'author:set' ]
      normalization_context:
        groups: [ 'author:get' ]
    itemOperations:
      put: ~
      get: ~
      delete: ~
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'author:list' ]
        filters: [ 'App\Filter\Author\Fullname', 'author.search_filter', 'author.order_filter' ]
