resources:
  App\Entity\Author:
    attributes:
      denormalization_context:
        groups: [ 'author:set', 'person:set' ]
      normalization_context:
        groups: [ 'author:get', 'person:get' ]
    itemOperations:
      put: ~
      get: ~
      delete: ~
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'author:list', 'person:list' ]
        filters:
          - App\Filter\Author\Fullname
          - App\Filter\Author\Person
          - author.search_filter
          - author.order_filter
