resources:
  App\Entity\Book\BookNotation:
    attributes:
      normalization_context:
        groups: ['notation_read']
      denormalization_context:
        groups: ['notation_write']
    collectionOperations:
      get:
        filters: ['book_notation.search_filter']
      post: ~
