resources:
  App\Entity\Book\BookFile:
    attributes:
      iri: http://schema.org/Book/BookFile
      routePrefix: /book
      normalization_context:
        groups: ['file_read']
    collectionOperations:
      post:
        controller: App\Controller\Book\BookFile\Post
        defaults:
          _api_receive: false
        validation_groups: [Default, file_create]
        swagger_context:
          consumes: [multipart/form-data]
          parameters:
            - in: formData
              name: file
              type: file
              description: The file to upload
    itemOperations:
      get:
        controller:
