resources:
  App\Entity\PaperBook:
    attributes:
      denormalization_context:
        groups: ['book:set']
      normalization_context:
        groups: [ 'electronicBook:get', 'book:get', 'file_read' ]
    itemOperations:
      put: ~
      get: ~
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'book:list' ]
