resources:
  App\Dto\Resources\Stats:
    itemOperations:
      get:
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false

    collectionOperations:
      get: ~
