resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: ['get_user']
      denormalization_context:
        groups: ['create_user']
    itemOperations:
      put: ~
      delete: ~
      get: ~
    collectionOperations:
      get:
        normalization_context:
          groups: [ 'user:list' ]
