resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: ['get_user']
      denormalization_context:
        groups: ['create_user']
    itemOperations:
      put: ~
      delete: ~
      get: ~
      get_current:
        method: GET
        path: /users/loggedIn
        controller: App\Controller\User\GetCurrent
        defaults:
          _api_receive: false
        swagger_context:
          public: false
          summary: "Returns the profile of the logged in user."
          parameters:
            - name: 'Authorization'
              required: true
              in: 'header'
              description: 'Bearer token'
          responses:
            200:
              description: "json array with personal profile"
