resources:
  App\Entity\Book\ElectronicBookInformation\ElectronicBookInformation:
    attributes:
      route_prefix: /electronic_book_information
      denormalization_context:
        groups: [ 'electronicBookInformation:set' ]
      normalization_context:
        groups: [ 'electronicBookInformation:get' ]
    itemOperations:
      get: ~
      delete: ~

    collectionOperations:
      post:
        controller: \App\Controller\ElectronicBookInformationPost
        defaults:
          _api_receive: false
        validation_groups: [book_create]
        swagger_context:
          consumes: [multipart/form-data]
          parameters:
            - in: formData
              name: electronicBook
              type: file
              description: The electronic book to parse
      get: ~
