resources:
  App\Entity\Book\BookFile:
    attributes:
      iri: http://schema.org/Book/BookFile
      normalization_context:
        groups: ['file_read']
    collectionOperations:
      post:
        controller: App\Controller\Book\BookFile\Post
        defaults:
          _api_receive: false
        validation_groups: [Default, file_create]
        openapi_context:
          summary: Create a book file to link to a book
          description: Create a book file from an uploaded file or from a book uploaded to the electronic book parser
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  oneOf:
                  - name: file
                    type: file
                    description: The file to upload
                    required: false
                  - name: electronic_book_information_id
                    type: string
                    description: Use a book previously uploaded to the electronic book parser by specifying the id of the resulting ElectronicBookInformation resource
                    required: false
    itemOperations:
      get:
        controller:
