resources:
  App\Entity\Book\Cover:
    attributes:
      iri: http://schema.org/Book/Cover
      route_prefix: /book
      normalization_context:
        groups: ['file_read']
    collectionOperations:
      post:
        controller: App\Controller\Book\CreateCover
        defaults:
          _api_receive: false
        validation_groups: [Default, file_create]
        openapi_context:
          summary: Create a cover to link to a book
          description: Create a cover from an uploaded file or from a book uploaded to the electronic book parser
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  oneOf:
                    - name: file
                      type: file
                      description: The cover to upload
                      required: false
                    - name: electronic_book_information_image_id
                      type: string
                      description: Use a book previously uploaded to the electronic book parser by specifying one id of the resulting ElectronicBookInformation Image resources
                      required: false
    itemOperations:
      get:
        controller: App\Controller\Book\GetCover
