resources:
  App\Entity\Book\ReferenceGroup:
    attributes:
      denormalization_context:
        groups: ['referenceGroup:set']
      normalization_context:
        groups: ['referenceGroup:get']
    itemOperations:
      put: ~
      get: ~
      delete: ~
      sort:
        method: PUT
        controller: App\Controller\Book\ReferenceGroup\Order
        path: '/reference_groups/{id}/sort'
        openapi_context:
          summary: Sort the books in the group by the order they are given in the request body
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    books:
                      type: array
                      items:
                        type: string
                        description: The ReferenceGroupBookId

    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: [ 'referenceGroup:list' ]
